'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class AdminRegisterUser

    '''<summary>
    '''landlordEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents landlordEmail As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''landlordPassword control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents landlordPassword As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''landlordFirstName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents landlordFirstName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''landlordLastName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents landlordLastName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''FullDescrp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FullDescrp As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlFullDescrp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlFullDescrp As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''tenantEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tenantEmail As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tenantPassword control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tenantPassword As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ButtonRegisterTenant control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonRegisterTenant As Global.System.Web.UI.HtmlControls.HtmlButton
End Class
